package com.app.figmaai.backend.common.util

data class PreviewImage(
  val image: String,
  val prompt: String,
)

val previewImages = listOf(
  PreviewImage("https://arweave.net/tVyqh0Y-8WZ0BzPOxAWl4_W7geW22yN8f0__X_rBAVE", "Bali Beautiful Girl Coconut Ocean Temple Beach Sun Deep Sea"),
  PreviewImage("https://arweave.net/ddrJ2RKJXy3LOkxrpRARvc3lKwoOFyjrZZMZ6Rz-HmQ", "modern minimalistic logo for NFT project Sur"),
  PreviewImage("https://arweave.net/vjEWetAl4otEpo6pe3Qeu_UQY-oi0wSNzsaL0G1_vLw", "future of the world"),
  PreviewImage("https://arweave.net/h5_xuw0a6KoNiTAkI2O_TXciTB7pBxjB6sNXrRPsJNA", "Midday Pre-Historic British Realism"),
  PreviewImage("https://arweave.net/GGqXrC4s7X44fqDEWGBwnGX16uYMUYBZsb3h8kwcPZA", "Desertwave Japonism Biopunk Legopunk Indonesian-Style Gadgetpunk Nostalgiacore Psychic"),
  PreviewImage("https://arweave.net/ro-D9tsLUBe9Tdnv_F3lpZGwWmS51AUaPcScItrl2Mk", "Sur NFT Crypto project modern logo"),
  PreviewImage("https://arweave.net/Lt8VBqU5LbQpKOlys_ZiodHP7-F9RU1HmT7V4Hlf8uE", "Lightsaber Police Mushroomcore Chillwave"),
  PreviewImage("https://arweave.net/Fz1wz6VxbBe5bT2mo5hv2_tuXJk3qQWbQWhbwIUu2PY", "cosmos planet sun"),
  PreviewImage("https://arweave.net/x0NfNPpg-ZxLiU1t-PnuEq8jDpU_azpFL0mXrVmeHf8", "superhero knife king war victory"),
  PreviewImage("https://arweave.net/JaIVNZcx6GO5GXUe_f4hLIR_tr_IGPRD_Z_vkdEnfsA", "space planet girl Astronaut love"),
  PreviewImage("https://arweave.net/btHuLtdpPkIu7-dGEAHe7KAip0tpglDcdniXqwVrqHU", "Star Wars fight spaceship"),
  PreviewImage("https://arweave.net/Kex-_LlaaF_OlpGjKHYjxp5vohhWXH2-pEyzjq27--o", "coconut girl coconut beach ocean summer sun"),
  PreviewImage("https://arweave.net/PX3VszTLabHWimwZSL0VaE7qOLArZ1BWqlo_zB-zUaw", "minecraft fission reactor"),
  PreviewImage("https://arweave.net/5dgTO8zelNjT9vuhP0maL9kjW9lX5zhoCJ_yWqO80J0", "girl sun coconut beach papaya sushi"),
  PreviewImage("https://arweave.net/PPecDUFhFrMN78Aw8tdSmwCTTSlBi9ZWKzMVr1-Bjzo", "bali scooter summer coconut forest"),
  PreviewImage("https://arweave.net/kUoaPeXWQzdSOW9AdGiqycs5roS528_wnpCZIasYidw", "bali scooter summer coconut forest girl"),
  PreviewImage("https://arweave.net/LS_ig5jHLO3tvN_6qQ5BSx2-w7xIk3rxm6Xwy-U4YaM", "interdimensional tree"),
  PreviewImage("https://arweave.net/oyi_ut1hhr2jCoNg_oc8uYNM3oRgn3tFZWiVkD-P1Ac", "reinbow car Nissan mountain"),
  PreviewImage("https://arweave.net/bshkcps5aEHse5oNKwxzHeFtkStS61UjdW2Mpdw2xXM", "huge Yggdrasil"),
  PreviewImage("https://arweave.net/U8A2skSW9Q5pNRV22iYqb17neo-rRaR6rOjVRV4xq50", "flower tower From Another Realm"),
  PreviewImage("https://arweave.net/BVfzw0eatC3YbXPfKiAHyVdnOLrD9WVe_7oiA_wwQD4", "ape rare yacht hat"),
  PreviewImage("https://arweave.net/PkbRb3L57H66tTqxMd-qEhedtNiW56gkSXcXWf3Qkzc", "Tesla speed rain road"),
  PreviewImage("https://arweave.net/Ob1FVEllTByVyJpAepmc54ZTl2UbTXK5Tj_ca5mvcvw", "Elon Musk on Big Ben"),
  PreviewImage("https://arweave.net/djm2QGFPhZxXUAb7xcSL7VkKJ3I9MDp3ECGxRKyiEnQ", "dumbbell hurricane"),
  PreviewImage("https://arweave.net/LYpYtTF5XobaOgP5BP7RnbQjAkW1VNwrHsGB2e1Myr0", "Star Wars"),
  PreviewImage("https://arweave.net/q4j2sbD7gH8u3zjXChAqsSI8HXJh0v3SeRszc8ZHyUQ", "pine tree Ethereal Fantasy"),
  PreviewImage("https://arweave.net/SacdZD8TgWOnWuUIdzm_LiKGeDPO591XKJDBDFLWsSU", "uranium blockchain"),
  PreviewImage("https://arweave.net/IMaQ3nslhhai1XQrGYfHBurw7sxhWiiP6qHU4KNvR1s", "steampunk wallet"),
  PreviewImage("https://arweave.net/HsbTD9ouZjh8dP5mYJZmoSK0VRqae-ibzQct_d3Fal4", "electronic Arts"),
  PreviewImage("https://arweave.net/dqOSErUv1goWK5OQf5Fn6D2Rac3GMboGe9fOSjdfo9s", "gold orbit"),
  PreviewImage("https://arweave.net/UnV_Nt82H3Mrc-mHcMuhcofNAbFTrMujprrf3LKdHTk", "super dog"),
  PreviewImage("https://arweave.net/TjOHfYrabTZSN9WdNI-Ka0wkQqV0LPjk8mPtutX2c9M", "global train"),
  PreviewImage("https://arweave.net/Jp8GdhOi-hMhHTvsw-_t8RwlOmKpf9nXbOcV_FvRYII", "Volga with big engine"),
  PreviewImage("https://arweave.net/pfk4--wUUzLJI2abZqTnpOIVHAQfZ6e8eGm45NPtIkk", "crystal earth core"),
  PreviewImage("https://arweave.net/-636B3GFkYwWpcyoYdoJqdLxJROtHqZ-d3s_wt8HDbg", "car chain"),
  PreviewImage("https://arweave.net/YAUEWrX1NlZglIUlmNnae8PVzeFZMZ7OVt_6qp1Wwzs", "electronic ship"),
  PreviewImage("https://arweave.net/yFUu56A-7L721GY2NYt7VWE4sTyBUM74_OQ0w_qAo2I", "cosmic bmw"),
  PreviewImage("https://arweave.net/ZU5XRgfT9fjTLOMmDoVZWP_97NyaBfI7KVwT3gyJnSI", "the moon of magical forests"),
  PreviewImage("https://arweave.net/b5_9aFt1bDIqxRLGEyJf1E8616632VDO1EOD73hd8io", "cheshire cat"),
  PreviewImage("https://arweave.net/2glSFSo6B6KTNmhVxTaY6ic2gJ5FT0bsoMEnCiHNJgc", "angel enthusiast"),
  PreviewImage("https://arweave.net/m0PznUdUncvNXuQq2_XBxiKr2K7DuVjd28QP2RUW2m0", "Volga as Chevrolet"),
  PreviewImage("https://arweave.net/n32aspfvejD6axc1hF89SXfQbfJ0G-wd9c9sRKKyN50", "pineapple cat"),
  PreviewImage("https://arweave.net/k8U_j5X1CWk71rLlh4_J9o4WAxfDQ7fdih7Rkv9PuGk", "bright dark"),
  PreviewImage("https://arweave.net/_KZ0txJuhKTVWCs_xfLX5cum-X4irZJbxRa6FTNi4yo", "the month of magical forests"),
  PreviewImage("https://arweave.net/wTVhOfXILLaQJCq2s-j49kvXRo4axwNmVjr_CsHgUdg", "Ireland ocean"),
  PreviewImage("https://arweave.net/BAn66LXWe6v4g0nh_pUdERoxzSfslHLRX27WE3omvho", "ice penguin"),
  PreviewImage("https://arweave.net/kbRqut27dPRwXjPRCuiQ7F6x2mS3mD-Jf9BMgeL-ycA", "coconut penguin"),
  PreviewImage("https://arweave.net/2mMELOleuZfTAxcp0hsXJOAOLqkNufoK8wgCcp1gJ7M", "Room Ukrainian-Style Attic Postcyberpunk Christian Icon Fairycore Jupiter"),
  PreviewImage("https://arweave.net/nVQKODTV4sP5i3WMvX604udRH6Hru2X5ZSLD5KJrPFU", "cloverfield"),
  PreviewImage("https://arweave.net/CY5K5mlCciNEMciQH_d4NX3T_pryHAFhk8d25LKCQ0k", "Cheshire dog"),
)