spring:
  application:
    name: FigmaAI Backend
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
    #    url: jdbc:postgresql://ec2-44-206-11-200.compute-1.amazonaws.com:5432/d5dnv721dua1v4
    #    username: grrrdhummkvzkj
    #    password: 24b2a32ae578d061675022b14cf440cdb4734783aa713e59e8c27599f1605fd0

  sql:
    init:
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: validate
  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: PT5M
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    doc-expansion: none
    display-operation-id: true
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  writer-with-order-by-keys: true

server:
  cors:
    enabled: true
    configurations:
      - path: /**
        configuration:
          # When allowCredentials is true, allowedOrigins cannot contain the special value "*"
          # since that cannot be set on the "Access-Control-Allow-Origin" response header.
          # To allow credentials to a set of origins, list them explicitly or consider
          # using "allowedOriginPatterns" instead.
          allow-credentials: false
          allowed-headers: Content-Type,X-Requested-With,accept,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Authorization, token, figma, content-length, refresh-token
          allowed-methods: POST,PUT,GET,DELETE,PATCH,OPTIONS,HEAD,post,put,get,delete,patch,options,head
          allowed-origins: "*"
          exposed-headers: Location,Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Content-Length
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

web-security:
  role-access-restriction-paths:
    - methods: PUT
      paths:
        - /images/**
        - /figma/*
    - methods: POST
      paths:
        - /figma/*
        - /images/**
        - /authorize
    - methods: PATCH
      paths:
        - /figma/**
        - /images/**
    - methods: DELETE
      paths:
        - /users/log-out
        - /images/**
    - methods: GET
      paths:
        - /images/**

application:
  sig-key: ${SIG_KEY}
  key: ${KEY}
  dalle-key: ${DALLE_KEY}
  stable-key: ${STABLE_KEY}
  paypal-id: ${PAYPAL_ID}
  paypal-secret: ${PAYPAL_SECRET}
  paypal-url: "https://api-m.sandbox.paypal.com"
  default-user-energy-limit: 30
  default-user-tokens-limit-per-day: 10
  energy-renew-rate: PT6H
  lemon-key: ${LEMON_KEY}
  lemon-url: "https://api.lemonsqueezy.com"

  arweave-url: "https://arweave.net/"

logging:
  level:
    com.app.figmaai: debug

amazon:
  aws:
    secret-key: 2an/Pt5M+WK1aPAzzQwwxAxEHQ5ynMgbaIMjU5Qf
    access-key: AKIAV4EZHLUJSK3D56S5
    region: us-east-1