spring:
  application:
    name: SurNFT Backend
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  sql:
    init:
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: validate
  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: PT5M
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    doc-expansion: none
    display-operation-id: true
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  writer-with-order-by-keys: true

server:
  cors:
    enabled: true
    configurations:
      - path: /**
        configuration:
          # When allowCredentials is true, allowedOrigins cannot contain the special value "*"
          # since that cannot be set on the "Access-Control-Allow-Origin" response header.
          # To allow credentials to a set of origins, list them explicitly or consider
          # using "allowedOriginPatterns" instead.
          allow-credentials: false
          allowed-headers: Content-Type,X-Requested-With,accept,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Authorization, signature, address, content-length
          allowed-methods: POST,PUT,GET,DELETE,PATCH,OPTIONS,HEAD,post,put,get,delete,patch,options,head
          allowed-origins: "*"
          exposed-headers: Location,Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Content-Length
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

web-security:
  role-access-restriction-paths:
    - methods: PUT
      paths:
        - /address
        - /address/*
    - methods: POST
      paths:
        - /address/energy
        - /address/withdraw
        - /upload
    - methods: PATCH
      paths:
        - /nft/**
        - /address/**
    - methods: DELETE
      paths:
        - /nft/**

application:
  sig-key: ${SIG_KEY}
  key: ${KEY}
  dalle-key: ${DALLE_KEY}
  default-user-energy-limit: 30
  default-user-tokens-limit-per-day: 10
  energy-renew-rate: PT6H
  durability-repair-cost: 0.625
  level-up-car-cost: 100
  chain-id: 56
  car-level-distance-requirement:
    1: 100
    2: 300
    3: 500
    4: 1000
    5: 2000
  collection-prices:
    - 1.0
    - 3.0
    - 5.0
  admin-address: "0x691E1C66A852C5830d7Ba9a9e8C080F826D5ED01"
  contract-address: "0x68276a30375db070f7677091f08ee49b7ead6cda"
  collection-address: "0xe73711e8331aD93ca115A2AE4D1AFAc74E15D644"
  client-url: https://intensive-divine-mountain.bsc.discover.quiknode.pro/79d20c28b6e2219dd4c5e8e9599f6440a6627034/
  second-client-url: https://bsc-dataseed.nariox.org
  arweave-url: "https://arweave.net/"
  free-mint-enabled: false

probability.car:
  SUR:
    quality:
      proportions:
        common: 0.5
        uncommon: 0.25
        rare: 0.15
        epic: 0.06
        legendary: 0.04
    body:
      proportions:
        WORKER: 0.3
        BASIC: 0.5
        RACING: 0.1
        SUPERSPORT: 0.1
    efficiency:
      proportions:
        1-75: 0.01
        75-80: 0.09
        80-100: 0.8
        100-125: 0.1

logging:
  level:
    com.app.surnft: debug

amazon:
  aws:
    secret-key: ${AWS_SECRET_KEY}
    access-key: ${AWS_ACCESS_KEY}
    region: us-east-1