spring:
  application:
    name: Drivn Backend
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      continue-on-error: true
  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: PT5M
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    doc-expansion: none
    display-operation-id: true
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  writer-with-order-by-keys: true

server:
  cors:
    enabled: true
    configurations:
      - path: /**
        configuration:
          # When allowCredentials is true, allowedOrigins cannot contain the special value "*"
          # since that cannot be set on the "Access-Control-Allow-Origin" response header.
          # To allow credentials to a set of origins, list them explicitly or consider
          # using "allowedOriginPatterns" instead.
          allow-credentials: false
          allowed-headers: Content-Type,X-Requested-With,accept,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Authorization
          allowed-methods: POST,PUT,GET,DELETE,PATCH,OPTIONS,HEAD
          allowed-origins: "*"
          exposed-headers: Location,Access-Control-Allow-Origin,Access-Control-Allow-Credentials
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

web-security:
  role-access-restriction-paths:
    - methods: PUT
      paths:
        - /address/*
    - methods: PATCH
      paths:
        - /nft/*
        - /address/*

application:
  sig-key: poop
  key: 0x2342db94aae1023c489b4e0ed0ecd880df0353a0da0214b348ed43b1c601db5025c514b7557e530f75d90aa5d1e3e5de175b01d7ebdbe26a5dc87288ef3183b69bb886cc1622935339a9271fb98c7ce40c4270eca120bd92c9dd354171b7c466
  default-user-energy-limit: 30
  default-user-tokens-limit-per-day: 10
  energy-renew-rate: PT6H
  durability-repair-cost: 0.625
  level-up-car-cost: 100
  car-level-distance-requirement:
    1: 100
    2: 300
    3: 500
    4: 1000
    5: 2000
  admin-address: 0xa81A54123dcafb6C3056a8f513DE28ef699790D8
  contract-address: 0xe418eE8ec1Bca66FFa7E088e4656Cc628661043d
  client-url: https://intensive-divine-mountain.bsc.discover.quiknode.pro/79d20c28b6e2219dd4c5e8e9599f6440a6627034/

logging:
  level:
    com.app.drivn: debug
