spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

web-security:
  role-access-restriction-paths:
    - methods: GET, POST, DELETE, PATCH
      roles: ROLE_ADMIN
      paths:
        - /

application:
  sig-key: poop
