spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      continue-on-error: true
  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: PT5M

server:
  cors:
    enabled: true
    configurations:
      - path: /**
        configuration:
          # When allowCredentials is true, allowedOrigins cannot contain the special value "*"
          # since that cannot be set on the "Access-Control-Allow-Origin" response header.
          # To allow credentials to a set of origins, list them explicitly or consider
          # using "allowedOriginPatterns" instead.
          allow-credentials: false
          allowed-headers: Content-Type,X-Requested-With,accept,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Authorization
          allowed-methods: POST,PUT,GET,DELETE,PATCH,OPTIONS,HEAD
          allowed-origins: "*"
          exposed-headers: Location,Access-Control-Allow-Origin,Access-Control-Allow-Credentials

web-security:
  role-access-restriction-paths:
    - methods: PUT
      roles: ${application.base-role}
      paths:
        - /address/*

application:
  base-role: ROLE_USER
  sig-key: poop
  default-user-energy-limit: 30
  default-user-tokens-limit-per-day: 10
  energy-renew-rate: PT6H
  durability-repair-cost: 0.625

logging:
  level:
    com.app.drivn: debug
