spring:
  application:
    name: Drivn Backend
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: validate
  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: PT5M
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    doc-expansion: none
    display-operation-id: true
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  writer-with-order-by-keys: true

server:
  cors:
    enabled: true
    configurations:
      - path: /**
        configuration:
          # When allowCredentials is true, allowedOrigins cannot contain the special value "*"
          # since that cannot be set on the "Access-Control-Allow-Origin" response header.
          # To allow credentials to a set of origins, list them explicitly or consider
          # using "allowedOriginPatterns" instead.
          allow-credentials: false
          allowed-headers: Content-Type,X-Requested-With,accept,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Authorization, signature, address
          allowed-methods: POST,PUT,GET,DELETE,PATCH,OPTIONS,HEAD
          allowed-origins: "*"
          exposed-headers: Location,Access-Control-Allow-Origin,Access-Control-Allow-Credentials
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

web-security:
  role-access-restriction-paths:

application:
  sig-key: ${SIG_KEY}
  key: ${KEY}
  default-user-energy-limit: 30
  default-user-tokens-limit-per-day: 10
  energy-renew-rate: PT6H
  durability-repair-cost: 0.625
  level-up-car-cost: 100
  chain-id: 56
  car-level-distance-requirement:
    1: 100
    2: 300
    3: 500
    4: 1000
    5: 2000
  admin-address: "0xe418eE8ec1Bca66FFa7E088e4656Cc628661043d"
  contract-address: "0x68276a30375db070f7677091f08ee49b7ead6cda"
  collection-address: "0x34031C84Ee86e11D45974847C380091A84705921"
  client-url: https://intensive-divine-mountain.bsc.discover.quiknode.pro/79d20c28b6e2219dd4c5e8e9599f6440a6627034/
  arweave-url: "https://arweave.net/"

probability:
  car:
    quality.proportions:
      common: 0.5
      uncommon: 0.25
      rare: 0.15
      epic: 0.06
      legendary: 0.04
    body.proportions:
      WORKER: 0.3
      BASIC: 0.5
      RACING: 0.1
      SUPERSPORT: 0.1
    efficiency.proportions:
      1-75: 0.01
      75-80: 0.09
      80-100: 0.8
      100-125: 0.1

logging:
  level:
    com.app.drivn: debug
